# Generated by Django 4.2 on 2023-05-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shortName', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('webSite', models.URLField(null=True)),
                ('logoUrl', models.URLField(null=True)),
                ('parentId', models.IntegerField(null=True)),
                ('parentName', models.CharField(max_length=128, null=True)),
                ('membersHaveTaxCode', models.BooleanField(null=True)),
                ('hasChildren', models.BooleanField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
