# Generated by Django 4.2 on 2023-05-02 08:32

from django.db import migrations


def create_user_profiles(apps, schema_editor):

    UserModel = apps.get_model("users", "User")
    UserProfileModel = apps.get_model("users", "UserProfile")

    for user in UserModel.objects.all():
        UserProfileModel.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(
            create_user_profiles, reverse_code=migrations.RunPython.noop
        )
    ]
