# Generated by Django 4.2 on 2023-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('isDefault', models.BooleanField(null=True)),
                ('isSuperRole', models.BooleanField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
