# Generated by Django 4.2 on 2023-05-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('isDefault', models.BooleanField(null=True)),
                ('isSuperRole', models.BooleanField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
