# Generated by Django 4.2 on 2023-05-03 02:12

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description of site.', null=True)),
                ('code', models.CharField(blank=True, help_text='Unique code to identify this site (to RMQ).', max_length=8, null=True, unique=True)),
                ('show_admin_notice', models.BooleanField(default=False, help_text='Whether or not to show a site-specific notice in the Admin.')),
                ('admin_notice_color', colorfield.fields.ColorField(default='#CCCCCC', help_text='Color of site-specific notice in the Admin.', image_field=None, max_length=18, samples=[('#CCCCCC', 'Grey'), ('#009933', 'Green'), ('#FFAA00', 'Yellow'), ('#FF0000', 'Red')])),
                ('site', models.OneToOneField(help_text='Associated site.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profiles',
            },
        ),
    ]
